### ISSUE TITLE
Q: why accept need port?

### ISSUE THREAD

**Issue by L-jasmine** [second-state/wasmedge_wasi_socket#24]
wasm api  `pub fn sock_accept(fd: u32, port: u32, fd: *mut u32) -> u32;`

But the port should already be bound in api `pub fn sock_bind(fd: u32, addr: *mut WasiAddress, port: u32) -> u32;`

**Comment by hydai** [comment]
Good question. The definition in wasi socket: https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasi/inode-linux.cpp#L832-L841

```cpp
WasiExpect<INode> INode::sockAccept(uint16_t Port) noexcept {
  struct sockaddr_in ServerSocketAddr;
  ServerSocketAddr.sin_family = AF_INET;
  ServerSocketAddr.sin_addr.s_addr = INADDR_ANY;
  ServerSocketAddr.sin_port = htons(Port);
  socklen_t AddressLen = sizeof(ServerSocketAddr);

  if (auto NewFd =
          ::accept(Fd, reinterpret_cast<struct sockaddr *>(&ServerSocketAddr),
                   &AddressLen);
      unlikely(NewFd < 0)) {
    return WasiUnexpect(fromErrNo(errno));
  } else {
    INode New(NewFd);
    return New;
  }
}
```

Since we don't use any information from the `ServerSocketAddr`. It should be removed and the `port` is no needed anymore.

**Comment by hydai** [comment]
This is updated on the master branch of WasmEdge. And it will ship with 0.9.0 release. So we should also update this repo.

**Comment by vss96** [comment]
@hydai can I raise the pr for the same?

**Comment by hydai** [comment]
> @hydai can I raise the pr for the same?

Sure thing :-)

**Comment by hydai** [comment]
And please jump the version to 0.2.0 for the breaking changes: https://github.com/second-state/wasmedge_wasi_socket/blob/main/Cargo.toml#L3
