### ISSUE TITLE
Improvements and questions

### ISSUE THREAD

**Issue by KernelErr** [second-state/wasmedge_wasi_socket#32]
I noticed in `accept` function, it always returns a static address. I thought it may be a bug.

https://github.com/second-state/wasmedge_wasi_socket/blob/ad123cc17ea42fa764b85db3e7c310f4630b93d1/src/lib.rs#L254

In the meanwhile, in my fork(https://github.com/KernelErr/wasmedge_wasi_socket), I added `Debug, Clone, Copy` attribute to several structs. I think this may be useful for a library to let other people use. And there are still some unused virables.

**Comment by hydai** [comment]
Oh, this should be set dynamically, not a static address.
Could you fix it with a PR?
