### ISSUE TITLE
Resolve URL failed when using `wasmedge_wasi_socket::ToSocketAddrs`

### ISSUE THREAD

**Issue by dm4** [second-state/wasmedge_wasi_socket#87]
### Current State

Failed to resolve URL using `wasmedge_wasi_socket::ToSocketAddrs`.

### Expected

Resolve URL correctly using `wasmedge_wasi_socket::ToSocketAddrs`.

## Environment

- Hardware Architecture: x86_64
- Operating system: Ubuntu 22.04 (docker)
- Docker version: 24.0.2
- wasmedge_wasi_socket version: 0.5.0 (latest)

## Steps to Reproduce

```
git clone https://github.com/dm4/wasi-socket-resolve-issue.git
cd wasi-socket-resolve-issue
docker compose up -d
docker compose exec -it app bash

# in container
nslookup target-service
nslookup secondstate.io
wasmedge --env HOST_PORT=target-service:80 /socket-test.wasm
wasmedge --env HOST_PORT=secondstate.io:80 /socket-test.wasm
```

It's successfully resolving domains `target-service` and `secondstate.io using `nslookup`, but in wasm, only `secondstate.io` resolve correctly, the `target-service` failed to resolve.

```
root@91008e55650d:/# wasmedge --env HOST_PORT=target-service:80 /socket-test.wasm
HOST_PORT target-service:80
Err Os { code: 83, kind: Uncategorized, message: "Success" }

root@91008e55650d:/# wasmedge --env HOST_PORT=secondstate.io:80 /socket-test.wasm
HOST_PORT secondstate.io:80
Ok IntoIter([185.199.108.153:80, 185.199.109.153:80, 185.199.110.153:80, 185.199.111.153:80])
```

**Comment by dm4** [comment]
The domain is defined in [docker-compose.yml](https://github.com/dm4/wasi-socket-resolve-issue/blob/main/docker-compose.yml#L7) and managed by docker network.

**Comment by L-jasmine** [comment]
I have found that Docker provides its own DNS resolver at 127.0.0.11:53. So, I believe the target-service is defined there. In version 0.5, it is possible to change the DNS server it connects to by passing the `DNS_SERVER` environment variable. Therefore, I think it may be necessary to change it to 127.0.0.11:53.

**Comment by dm4** [comment]
Thanks. After passing the `DNS_SERVER` env environment variable, `wasmedge_wasi_socket::ToSocketAddrs` could resolve hostname correctly.

```
root@28e454056171:/# nslookup target-service
Server:         127.0.0.11
Address:        127.0.0.11#53
Non-authoritative answer:
Name:   target-service
Address: 172.29.0.3

root@28e454056171:/# wasmedge --env HOST_PORT=target-service:80 /socket-test.wasm
HOST_PORT target-service:80
Err Os { code: 83, kind: Uncategorized, message: "Success" }

root@28e454056171:/# wasmedge --env HOST_PORT=target-service:80 --env DNS_SERVER=127.0.0.11:53 /socket-test.wasm
HOST_PORT target-service:80
Ok IntoIter([172.29.0.3:80])
```
